joplin-server:
  image:
    # -- image repository
    repository: joplin/server
      # -- image tag
    tag: 2.7.3-beta
    # -- image pull policy
    pullPolicy: IfNotPresent

  # -- environment variables. See [image docs](https://github.com/laurent22/joplin) for more details.
  # @default -- See below
  env:
    # -- Set the container timezone
    TZ: America/Los_Angeles
    # -- joplin-server base URL
    APP_BASE_URL: https://joplin-server.k8s.lan
    # -- joplin-server listening port (same as Service port)
    APP_PORT: 22300
    # -- Use pg for postgres
    DB_CLIENT: pg
    # -- Postgres DB Host
    POSTGRES_HOST:  joplin-server-postgresql
    # -- Postgres DB port
    POSTGRES_PORT:  5432
    # -- Postgres DB name
    POSTGRES_DATABASE: joplin
    # -- Postgres DB Username
    POSTGRES_USER: joplin
    # -- Postgres DB password
    #POSTGRES_PASSWORD:  # joplin-pass

  envFrom:
    - secretRef:
        name: joplin-server-secrets


  # -- Configures service settings for the chart.
  # @default -- See values.yaml
  service:
    main:
      ports:
        http:
          port: 22300

  ingress:
    # -- Enable and configure ingress settings for the chart under this key.
    # @default -- See values.yaml
    main:
      enabled: true
      primary: true
      ingressClassName: "public"
      annotations:
        cert-manager.io/cluster-issuer: local-ca-issuer
      hosts:
        - host: joplin-server.k8s.lan
          paths:
            - path: /
              pathType: Prefix
              port: 22300
      tls:
        - secretName: joplin-server-tls
          hosts:
            - joplin-server.k8s.lan

  # -- Enable and configure postgresql database subchart under this key.
  #    For more options see [postgresql chart documentation](https://github.com/bitnami/charts/tree/master/bitnami/postgresql)
  # @default -- See values.yaml
  postgresql:
    enabled: true
    image:
      repository: bitnami/postgresql
      tag: 14.1.0
    postgresqlUsername: joplin
    postgresqlDatabase: joplin
    existingSecret: joplin-server-secrets
    persistence:
      enabled: true
      storageClass: nfs-synology
    sercurityContext:
      fsGroup: 100  #nfs-client: 1000
    containerSecurityContext:
      runAsUser: 1024  #nfs-client 1000

    # If storageClass == nfs-client, the following should be set
    # sercurityContext:
    #   fsGroup: 1000
    # containerSecurityContext:
    #   runAsUser: 1000


postgresql:
  enabled: true
