#!/bin/bash
HTOP_HIEGHT=15

if [ "$1" != "" ]; then
  cd $1
fi

tmux new-session -s ss\; \
  setw -ag window-status-current-style "bg=red" \; \
  set-option -ag pane-active-border-style "fg=red" \; \
  split-window -v \; \
  split-window -v -p 85 \; \
  split-window -h \; \
  resize-pane -t 0 -y 8 \; \
  resize-pane -t 1 -y 15 \; \
  send-keys -t 0 'htop' C-m \; \
  send-keys -t 1 'watch docker ps -a' C-m \; \
  select-pane -t 2 \; \
  \
  new-window \; \
  split-window -v \; \
  split-window -h \; \
  resize-pane -t 0 -y 15 \; \
  resize-pane -t 1 -x 75 \; \
  send-keys -t 0 'watch docker ps -a' C-m \; \
  \
  new-window \; \
  split-window -v \; \
  split-window -h \; \
  resize-pane -t 0 -y 15 \; \
  resize-pane -t 1 -x 75 \; \
  send-keys -t 0 'watch docker ps -a' C-m \; \
  \
  new-window \; \
  split-window -v \; \
  split-window -h \; \
  resize-pane -t 0 -y 15 \; \
  resize-pane -t 1 -x 75 \; \
  send-keys -t 0 'watch docker ps -a' C-m \; \
  \
  select-window -t 0 \;
