{{ if .Values.vault_backup.enabled }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vault-backups
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 8Gi
  storageClassName: nfs-synology-backups
{{ end }}
