#!/bin/bash
HTOP_HIEGHT=8

if [ "$1" != "" ]; then
  cd $1
fi

tmux new-session \; \
  setw -ag window-status-current-style "bg=red" \; \
  set-option -ag pane-active-border-style "fg=red" \; \
  split-window -v \; \
  split-window -v -p 85 \; \
  split-window -h -p 66 \; \
  split-window -h -p 50 \; \
  select-pane -t 2 \; \
  split-window -v -p 50 \; \
  resize-pane -t 0 -y 8 \; \
  resize-pane -t 1 -y 15 \; \
  send-keys -t 0 'htop' C-m \; \
  send-keys -t 1 'watch docker ps -a' C-m \; \
  select-pane -t 2 \; 
