argo-rollouts:
  dashboard:
    enabled: true
    ingress:
      enabled: true
      ingressClassName: public
      annotations:
        cert-manager.io/cluster-issuer: local-ca-issuer
      hosts:
        - argo-rollouts.k8s.lan
      tls:
        - secretName: argo-rollouts-tls
          hosts:
            - argo-rollouts.k8s.lan

