- name: Add Jetstack Helm Repo
  kubernetes.core.helm_repository:
    name: jetstack
    repo_url: "https://charts.jetstack.io"

- name: Deploy cert-manager
  kubernetes.core.helm:
    name: cert-manager
    chart_ref: jetstack/cert-manager
    release_namespace: cert-manager
    create_namespace: true
    values:
      installCRDs: true
      version: "{{ version.cert_manager }}"
      ingressShim:
        defaultIssuerName: letsencrypt-staging
        defaultIssuerKind: ClusterIssuer

- name: Deploy Letsencrypt staging cert issuer
  kubernetes.core.k8s:
    state: present
    src: ./manifests/letsencrypt-clusterissuer-staging.yaml
    namespace: cert-manager

- name: Deploy Letsencrypt production cert issuer
  kubernetes.core.k8s:
    state: present
    src: ./manifests/letsencrypt-clusterissuer-production.yaml
    namespace: cert-manager

- name: Deploy Local CA cert Issuer
  kubernetes.core.k8s:
    state: present
    src: ./manifests/ca-clusterissuer.yaml
    namespace: cert-manager
