apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-flinnlab-com
  namespace: argocd
spec:
  secretName: argocd-server-tls
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  subject:
    organizations:
      - flinnlab
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
    - client auth
  dnsNames:
    - argocd.flinnlab.com
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
