FROM docker

RUN apk add --no-cache vim tmux curl openssh sudo 
RUN apk add --no-cache python3

RUN adduser --disabled-password --gecos '' "joseph"
RUN groupadd sudo
RUN adduser "joseph" sudo

RUN echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers

#USER joseph
WORKDIR /home/joseph

ENTRYPOINT ["sh"]
