FROM ubuntu:bionic


ENV DOCKER_USER joseph

RUN apt-get update && \
    apt-get install -y sudo && \
    adduser --disabled-password --gecos '' "$DOCKER_USER" && \
    adduser "$DOCKER_USER" sudo && \
    echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers && \
    touch /home/$DOCKER_USER/.sudo_as_admin_successfull && \
    rm -rf /var/lib/apt/lists/*

RUN yes | sudo unminimize && \
    sudo apt-get install -y man-db bash-completion build-essential curl openssh-client openssh-server && \
    sudo rm -rf /var/lib/apt/lists/*

RUN sudo apt-get update && \
    sudo apt-get install -y man-db bash-completion build-essential curl openssh-client && \
    sudo apt-get install -y tmux && \
    sudo apt-get install -y neovim && \
    sudo rm -rf /var/lib/apt/lists/*

RUN sudo apt-get update && \
    sudo apt-get install -y python3 && \
    sudo rm -rf /var/lib/apt/lists/*




USER "$DOCKER_USER"

WORKDIR "/home/$DOCKER_USER"
