{{- range $argoApps := .Values.argoApps.manifests }}

{{ if $argoApps.enabled }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $argoApps.name }}
  namespace: argocd
spec:
  destination:
    namespace: {{ $argoApps.namespace }}
    server: 'https://kubernetes.default.svc'
  source:
    path: {{ $argoApps.gitPath }}
    repoURL: {{ $argoApps.gitRepo }}
    targetRevision: {{ $argoApps.targetRevision }}
  project: {{ $argoApps.projectName }}
  syncPolicy:
  {{- if $argoApps.automated }}
    automated:
      {{- toYaml $argoApps.automated | nindent 6 }}
  {{- end }}
  {{- if $argoApps.syncOptions }}
    syncOptions:
    {{- range $argoApps.syncOptions }}
      - {{ . }}
    {{- end }}
  {{- end }}
{{- end }}
{{- end }}
