apiVersion: v1
kind: Secret
metadata:
  name: joplin-server-secrets
type: Opaque
data:
  # You can include additional key value pairs as you do with Opaque Secrets
  postgresql-password: REPLACE
  postgresq-postgres-password: REPLACE
  POSTGRES_PASSWORD: REPLACE
