---
- hosts: "{{ targets }}"
  become: true
  become_user: root
  tasks:
    - import_tasks: task-components/safe-shutdown-node.yaml
      when: "targets == 'nodes' or 'nodes' in group_names"

    - import_tasks: task-components/shutdown.yaml
      when: "targets == 'nas' or 'nas' in group_names"
