---
- hosts: "{{ targets }}"
  become: true
  become_user: root
  serial: 1
  tasks:
    - name: Update apt repo and cache
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

    - name: Upgrade packages
      apt: upgrade=dist force_apt_get=yes

    - name: Check if a reboot is needed
      register: reboot_required_file
      stat: path=/var/run/reboot-required get_md5=no

    - name: reboot nodes
      import_tasks: task-components/safe-reboot-node.yaml
      when: "reboot_required_file.stat.exists and targets == 'nodes' or 'nodes' in group_names"

    - name: reboot nas
      import_tasks: task-components/reboot.yaml
      when: "reboot_required_file.stat.exists and targets == 'nas' or 'nas' in group_names"
