---
- name: Check Cluster Data
  hosts: cluster
  remote_user: root

  tasks:
  - name: snap version
    shell: 
      cmd: snap --version || echo "[!!!] snap not installed"
    register: snap_out
  - name: microk8s version
    shell: 
      cmd: microk8s config || echo "[!!!] microk8s not installed"
    register: mk8s_out

  - debug:
      var: snap_out.stdout_lines
  - debug:
      var: mk8s_out.stdout_lines
