apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: bitwardenclisecrets.bitwarden.com
spec:
  group: bitwarden.com
  names:
    kind: BitwardenCLISecret
    plural: bitwardenclisecrets
    singular: bitwardenclisecret
  scope: Namespaced
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        x-kubernetes-preserve-unknown-fields: true
    subresources:
     status: {}

