argo-workflows:
  server:
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: local-ca-issuer
      ingressClassName: public
      pathType: Prefix
      hosts:
        - argo-workflows.k8s.lan
      tls:
        - secretName: argo-workflows-tls
          hosts:
            - argo-workflows.k8s.lan

