docker-registry:
  persistence:
    enabled: true
    storageClass: nfs-synology
    size: 40Gi

  ingress:
    enabled: true
    className: public
    annotations:
      cert-manager.io/cluster-issuer: local-ca-issuer
      nginx.ingress.kubernetes.io/proxy-body-size: "0"
    path: /
    hosts:
      - registry.k8s.lan
    tls:
      - secretName: registry-tls
        hosts: 
          - registry.k8s.lan
