vault: 
  server:
    ingress:
      enabled: 
      hosts:
        - host: &domain vault.k8s.lan
          paths:
            - /
      tls:
        - secretName: vault-ssl
          hosts:
            - *domain

    dataStorage:
      storageClass: nfs-synology

    extraEnvironmentVars:
      VAULT_ADDR: https://127.0.0.1:8200
      VAULT_CACERT: /opt/vault/ca.crt
      VAULT_TLS_SERVER_NAME: *domain
 
    standalone:
      enabled: false
    ha:
      enabled: true
      raft:
        enabled: true
        setNodeId: true

        config: |
          ui = true
          listener "tcp" {
            tls_disable = 0
            address = "[::]:8200"
            cluster_address = "[::]:8201"
            tls_cert_file = "/opt/vault/tls.crt"
            tls_key_file = "/opt/vault/tls.key"
            tls_client_ca_file = "/opt/vault/ca.crt"
          }

          storage "raft" {
            path = "/vault/data"
            #retry_join {
            #  leader_api_addr = "https://vault-active.vault.svc.cluster.local:8200"
            #  leader_ca_cert_file = "/opt/vault/ca.crt"
            #  leader_client_cert_file = "/opt/vault/tls.crt"
            #  leader_client_key_file = "/opt/vault/tls.key"
            #}
            retry_join {
              leader_api_addr = "https://vault-0.vault-internal:8200"
              leader_ca_cert_file = "/opt/vault/ca.crt"
              leader_client_cert_file = "/opt/vault/tls.crt"
              leader_client_key_file = "/opt/vault/tls.key"
            }
            retry_join {
              leader_api_addr = "https://vault-1.vault-internal:8200"
              leader_ca_cert_file = "/opt/vault/ca.crt"
              leader_client_cert_file = "/opt/vault/tls.crt"
              leader_client_key_file = "/opt/vault/tls.key"
            }
            retry_join {
              leader_api_addr = "https://vault-2.vault-internal:8200"
              leader_ca_cert_file = "/opt/vault/ca.crt"
              leader_client_cert_file = "/opt/vault/tls.crt"
              leader_client_key_file = "/opt/vault/tls.key"
            }
          }

          service_registration "kubernetes" {}

    volumes: 
      - name: vault-tls
        secret:
          secretName: vault-tls

    #  - name: backups
    #    persistentVolumeClaim:
    #      claimName: vault-backups

    volumeMounts:
      - name: vault-tls
        mountPath: /opt/vault
        readOnly: true
    #  - name: backups
    #    mountPath: /opt/vault


vault_backup:
  enabled: true

vault_manual_tls_certs:
  enabled: true

pre_install_hook:
  enabled: false
