vault: 
  server:
    ingress:
      enabled: false
      annotations:
        cert-manager.io/cluster-issuer: local-ca-issuer
      hosts:
        - host: vault.k8s.lan
          paths:
            - /
      tls:
        - secretName: vault-ssl
          hosts:
            - vault.k8s.lan

    dataStorage:
      storageClass: nfs-synology

    extraEnvironmentVars:
      VAULT_CACERT: /vault/userconfig/tls-ca/ca.crt

    extraVolumes:
      - type: secret
        name: tls-ca
      - type: secret
        name: tls-server
 
    standalone:
      enabled: false
    ha:
      enabled: true
      raft:
        enabled: true
        setNodeId: true

        config: |
          ui = true
          listener "tcp" {
            tls_disable = 1
            address = "[::]:8200"
            cluster_address = "[::]:8201"
            tls_cert_file = "/vault/userconfig/tls-server/vault.crt"
            tls_key_file = "/vault/userconfig/tls-server/vault.key"
            tls_client_ca_file = "/vault/userconfig/tls-ca/ca.crt"
            #tls_client_ca_file = "/vault/userconfig/tls-server/client-auth-ca.pem"
          }

          storage "raft" {
            path = "/vault/data"
            retry_join {
              leader_api_addr = "https://vault-0.vault-internal:8200"
              leader_ca_cert_file = "/vault/userconfig/tls-ca/ca.crt"
              leader_client_cert_file = "/vault/userconfig/tls-server/vault.crt"
              leader_client_key_file = "/vault/userconfig/tls-server/vault.key"
            }
            retry_join {
              leader_api_addr = "https://vault-1.vault-internal:8200"
              leader_ca_cert_file = "/vault/userconfig/tls-ca/ca.crt"
              leader_client_cert_file = "/vault/userconfig/tls-server/vault.crt"
              leader_client_key_file = "/vault/userconfig/tls-server/vault.key"
            }

            retry_join {
              leader_api_addr = "https://vault-2.vault-internal:8200"
              leader_ca_cert_file = "/vault/userconfig/tls-ca/ca.crt"
              leader_client_cert_file = "/vault/userconfig/tls-server/vault.crt"
              leader_client_key_file = "/vault/userconfig/tls-server/vault.key"
            }

          }

          service_registration "kubernetes" {}

    #volumes: 
    #  - name: backups
    #    persistentVolumeClaim:
    #      claimName: vault-backups

    #volumeMounts:
    #  - name: backups
    #    mountPath: /opt/vault


vault_backup:
  enabled: true

