vault:
  server:
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: local-ca-issuer
      hosts:
        - host: vault.k8s.lan
          paths:
            - /
      tls:
        - secretName: vault-ssl
          hosts:
            - vault.k8s.lan

    dataStorage:
      storageClass: nfs-synology

    volumes: 
      - name: backups
        persistentVolumeClaim:
          claimName: vault-backups

    volumeMounts:
      - name: backups
        mountPath: /opt/vault


vault_backup:
  enabled: true

