vault:
  server:
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: local-ca-issuer
      hosts:
        - host: vault.k8s.lan
          paths:
            - /
      tls:
        - secretName: vault-ssl
          hosts:
            - vault.k8s.lan

    dataStorage:
      storageClass: nfs-synology

    extraEnvironmentVars:
      VAULT_CACERT: /vault/userconfig/tls-ca/ca.crt

    extraVolumes:
      - type: secret
        name: tls-server
      - type: secret
        name: tls-ca

    standalone:
      enabled: false
    ha:
      enabled: true
      raft:
        enabled: true
        setNodeId: true

        config: |
          ui = true
          listener "tcp" {
            tlsDisable = 1
            address = "[::]:8200"
            cluster_address = "[::]:8201"
            #tls_cert_file = "/vault/userconfig/tls-server/fullchain.pem"
            #tls_key_file = "/vault/userconfig/tls-server/server.key"
            #tls_client_ca_file = "/vault/userconfig/tls-server/client-auth-ca.pem"
          }

          storage "raft" {
            path = "/vault/data"
              retry_join {
              leader_api_addr = "https://vault-0.vault-internal:8200"
              #leader_ca_cert_file = "/vault/userconfig/tls-ca/ca.crt"
              #leader_client_cert_file = "/vault/userconfig/tls-server/server.crt"
              #leader_client_key_file = "/vault/userconfig/tls-server/server.key"
            }
            retry_join {
              leader_api_addr = "https://vault-1.vault-internal:8200"
              #leader_ca_cert_file = "/vault/userconfig/tls-ca/ca.crt"
              #leader_client_cert_file = "/vault/userconfig/tls-server/server.crt"
              #leader_client_key_file = "/vault/userconfig/tls-server/server.key"
            }

            retry_join {
              leader_api_addr = "https://vault-2.vault-internal:8200"
              #leader_ca_cert_file = "/vault/userconfig/tls-ca/ca.crt"
              #leader_client_cert_file = "/vault/userconfig/tls-server/server.crt"
              #leader_client_key_file = "/vault/userconfig/tls-server/server.key"
            }

            autopilot {
              cleanup_dead_servers = "true"
              last_contact_threshold = "200ms"
              last_contact_failure_threshold = "10m"
              max_trailing_logs = 250000
              min_quorum = 5
              server_stabilization_time = "10s"
            }

          }

          service_registration "kubernetes" {}

    #volumes: 
    #  - name: backups
    #    persistentVolumeClaim:
    #      claimName: vault-backups

    #volumeMounts:
    #  - name: backups
    #    mountPath: /opt/vault


vault_backup:
  enabled: true

