vault: 
  server:
    ingress:
      enabled: 
      annotations:
        cert-manager.io/cluster-issuer: local-ca-issuer
      hosts:
        - host: &domain vault.k8s.lan
          paths:
            - /
      tls:
        - secretName: vault-ssl
          hosts:
            - *domain

    dataStorage:
      storageClass: nfs-synology

    extraEnvironmentVars:
      VAULT_CACERT: /vault/opt/ca.crt
      VAULT_TLS_SERVER_NAME: *domain

    #extraVolumes:
    #- type: secret
    #  name: tls-ca
    #- type: secret
    #  name: tls-server
 
    standalone:
      enabled: false
    ha:
      enabled: true
      raft:
        enabled: true
        setNodeId: true

        config: |
          ui = true
          listener "tcp" {
            #tls_disable = 1
            address = "[::]:8200"
            cluster_address = "[::]:8201"
            tls_cert_file = "/vault/opt/tls.crt"
            tls_key_file = "/vault/opt/tls.key"
            tls_client_ca_file = "/vault/opt/ca.crt"
          }

          storage "raft" {
            path = "/vault/data"
            retry_join {
              leader_api_addr = "https://vault.vault.svc.cluster.local:8200"
              tls_cert_file = "/vault/opt/tls.crt"
              tls_key_file = "/vault/opt/tls.key"
              tls_client_ca_file = "/vault/opt/ca.crt"
            }
          }

          service_registration "kubernetes" {}

    volumes: 
      - name: vault-tls
        secret:
          secretName: vault-ssl

    #  - name: backups
    #    persistentVolumeClaim:
    #      claimName: vault-backups

    volumeMounts:
      - name: vault-tls
        mountPath: /opt/vault
        readOnly: true
    #  - name: backups
    #    mountPath: /opt/vault


vault_backup:
  enabled: true

vault_manual_tls_certs:
  enabled: false

pre_install_hook:
  enabled: false
