apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: photoprism-secrets
  namespace: photoprism
spec:
  encryptedData:
    PHOTOPRISM_ADMIN_PASSWORD: AgCah4n/ibalASRmF7TdCaDIYczK57LrZk6V2L/KbadK7cUFcdGXUKH5gH7n3son/jup45N2TmV+m9H8OF2sp/hlKYMqBdgq4gbkUz5+5/QJgSOrGVtjS1LEbSf+tS46rSUQku0/VIBfFm/vQEPdjJHY215XwJp3FBYUZT/sYrLkoPGkrsITR/J9LFwgdIYIN7vqV8EABsbWAMSzUqtUPCd0HixN6Bu1YF14/JvnPUwQrMbcvXgVKPLP3dxvjZChE/ml6ZM5OXlWfm1vCJaMMd2pAfXmqH1jrap2f3Q2O9Kt+ogVE1NZkBXiVFCroSVJnNLdo+WmpS/iJ9hPHC/wZOqaDiYMsjJBLm/IroSwlj6OEt572rkv/T5atyCK5BZZdSxBSQxhsoao4SJJhWky7YYezNFVzf0tQ96MVhBEZ8e7uf01MS0iS4uHNhN8R2VU6ccp5r5Tgc0/e85BhNGUQAvSgZldtVZokxjZ878fLRpdlnaNqTGFsGs7nR8P5jtA3MHj56hj05VH//fDIj89JtFGpO4CdouERYA7EI58YME+yWSkWcqA+BCl2FN2izjW0wtvBACIYAbbd2Hv5Mab98LhdKxiYchVEoU6U89PLHEoiTsqo72Hl1sOLpP/4VfTCFervIlss9Xm8w+SlFlDVEXgyp+CcVVXuvrqlLcynnuPVH1Q/hNQ6dR1RW78nDbjHM9TxgMV+tW20cJ0Srpi9PRJt+IU
    PHOTOPRSIM_DATABASE_PASSWORD: AgCah916+yJTtLhbDiZvDKeZkjPSHG3CBFljnonGltRDF0W4VTn46EQbDkzZOe/xcOwRBMLO0T0W9rqTV6miPNKvCIKufzS3h9m7UvpQzzVLB3ACRz/r3n+u8EN7UdEVVOZqiQTeaWDAmMYxOB0Co661w/mViiMyCxWK8/D4ruLw1+PxuO3Clra7VPMQKbBQf+7ZBf43aeKmlNliD20PFwIokizxzsOk2yo3yXzMBt30pTZNBHNEePDWJQThnO8ohcu46wqzg6df1r787zr5unAKRblJj1SjaOcjcduUjBxSGME74cxCbPU6/IJoGppaJEkL4GqkB9LjeqSyyySGwpVQqStRwPdOX8TCKHe0m57fhq59rDcDgWAQ55RfyK9+aSGGea1udgtYz6Da5FCOuunqFZCGHWRV7IJCUVEGAcXa/LmIS4CQ7mNBQR85BrectN+4ArlTrFfcv9PWn+xMh56vcaZcVopy9n5i7xq1bGIPyFEikJAX3xuh+66ZH5rkV44VdUj5stbZoYdmlxCecs1IOvDqOVqQUvfFhvvjDe4662giWkVrbJFOj+nJ0S8fm6bRW543GTVErJ/zZtexyE4qfKA5chju7UidwkW1E4kz3cRKsuDUDIsdxci3szA1Juy1paFgs3ncUVzcpPOyMdU0lCkqOXQGU0KSiSfW//APiANzTNRdKdU7ijPg0HQYLkkersChuPJnwcg7XehmEy62VLhQ
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: photoprism-secrets
      namespace: photoprism
    type: Opaque

