#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/k8s-at-home/library-charts/tree/main/charts/stable/common/values.yaml
#
photoprism:
  image:
    # -- image repository
    repository: photoprism/photoprism
    # -- image tag
    # @default -- chart.appVersion
    tag:
    # -- image pull policy
    pullPolicy: IfNotPresent

  # -- environment variables. See [image docs](https://docs.photoprism.org/getting-started/config-options/) for more details.
  # @default -- See below
  env:
    # -- Set the container timezone
    TZ: America/Los_Angeles
    # -- Photoprism storage path
    PHOTOPRISM_STORAGE_PATH: /photoprism/storage
    # -- Photoprism originals path
    PHOTOPRISM_ORIGINALS_PATH: /photoprism/originals
    # -- Disable authentication / password protection
    PHOTOPRISM_PUBLIC: "false"
    # -- Sets UID Photoprism runs under.
    UID:  # 1000
    # -- Sets GID Photoprism runs under.
    GID:  # 1000
    # -- Sets UMASK.
    UMASK:  # 0000
    # -- Database driver (sqlite, mysql)
    PHOTOPRISM_DATABASE_DRIVER: mysql
    # -- Database host incl. port
    PHOTOPRISM_DATABASE_SERVER: photoprism-mariadb:3306
    # -- Database schema name
    PHOTOPRISM_DATABASE_NAME: photoprism
    # -- Database user name
    PHOTOPRISM_DATABASE_USER: photoprism
  envFrom:
    - photoprism-secrets

  # -- Configures service settings for the chart.
  # @default -- See values.yaml
  service:
    main:
      ports:
        http:
          port: 2342

  ingress:
    # -- Enable and configure ingress settings for the chart under this key.
    # @default -- See values.yaml
    main:
      enabled: true
      primary: true
      ingressClassName: "public"
      annotations:
        cert-manager.io/cluster-issuer: local-ca-issuer
      hosts:
        - host: photoprism.k8s.lan
          paths:
            - path: /
              pathType: Prefix
              port: 2342
      tls:
        - secretName: photoprism-tls
          hosts:
            - photoprism.k8s.lan

  # -- Configure persistence settings for the chart under this key.
  # @default -- See values.yaml
  persistence:
    config:
      enabled: true
      mountPath: /photoprism/storage
      storageClass: nfs-synology
      type: pvc
      accessMode: ReadWriteOnce
      size: 50Gi
      retain: true

    originals:
      enabled: true
      mountPath: /photoprism/originals
      storageClass: nfs-synology
      type: pvc
      accessMode: ReadWriteOnce
      size: 50Gi
      retain: true

  # -- Enable and configure mariadb database subchart under this key.
  #    For more options see [mariadb chart documentation](https://github.com/bitnami/charts/tree/master/bitnami/mariadb)
  # @default -- See values.yaml
  mariadb:
    enabled: true
    architecture: standalone
    auth:
      database: photoprism
      username: photoprism
      existingSecret: mariadb-secrets
    primary:
      persistence:
        enabled: enabled
        storageClass: nfs-synology
        type: pvc
        accessMode: ReadWriteOnce
        size: 25Gi
        retain: true
