name: Build & Release

on:
  push:
    branches:
      - main

jobs:
  build-n-release:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Repo
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f  # v2.3.4

      - name: Get release version
        id: versions
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          current_version=$(hub release -L 1)
          file_version=$(grep version_stub .version | grep -o "[0-9].[0-9]")
          echo "current release version: $current_version"
          echo "version from file: $file_version"

          if [[ $($current_version | cut -d . -f "1 2") == "$file_verison" ]]; then
            new_version=$file_version.$(expr `echo $current_version | cut -d . -f 3` + 1)
          else
            new_version=$file_version.0
          fi

          echo "::set-output name=value::$new_version"

      - name: Build Ubuntu asset
        run: |
          mkdir -p dist/ubuntu
          ll -R ./dotfiles
          cp -R dotfiles/current/shared/* dist/ubuntu
          cp -R dotfiles/current/ubuntu/* dist/ubuntu
          zip ubuntu-dotfiles.zip dist/ubuntu

      - name: Build Mac asset
        run: |
          mkdir -p dist/mac
          cp -R dotfiles/current/shared/* dist/mac
          cp -R dotfiles/current/ubuntu/* dist/mac
          zip ubuntu-dotfiles.zip dist/mac

      - name: Create release
        uses: ncipollo/release-action@95215a3cb6e6a1908b3c44e00b4fdb15548b1e09
        with:
          artifacts: |
            dist/ubuntu-dotfiles.zip
            dist/mac-dotfiles.zip
            bin/*
          commit: ${{ github.sha }}
          tag: v${{ steps.version.outputs.value }}
          name: "Version ${{ steps.version.outputs.value }}"
          token: ${{ secrets.GITHUB_TOKEN }}
