name: Build & Release

on:
  push:
    branches:
      - main

jobs:
  build-n-release:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Repo
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f  # v2.3.4

      - name: Get release version
        id: version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          current_tag=$(hub release -L 1)
          current_version=${current_tag:1}
          file_version=$(grep version_stub .version | grep -o "[0-9].[0-9]")
          echo "current release version: $current_version"
          echo "version from file: $file_version"

          if [[ $($current_version | cut -d . -f "1 2") == "$file_verison" ]]; then
            new_version=$file_version.$(expr $(echo $current_version | cut -d . -f 3) + 1)
          else
            new_version=$file_version.0
          fi

          echo "::set-output name=value::$new_version"

      - name: Build Ubuntu asset
        env:
          VERSION: ${{ steps.version.outputs.value }}
        run: |
          mkdir -p dist/ubuntu-dotfiles
          cp -a dotfiles/current/shared/. dist/ubuntu-dotfiles
          cp -a dotfiles/current/ubuntu/. dist/ubuntu-dotfiles
          cd dist
          echo "$VERSION" > dist/ubuntu-dotfiles/.version
          zip -r ubuntu-dotfiles-$VERSION.zip ubuntu-dotfiles

      - name: Build Mac asset
        env:
          VERSION: ${{ steps.version.outputs.value }}
        run: |
          mkdir -p dist/mac-dotfiles
          cp -a dotfiles/current/shared/. dist/mac-dotfiles
          cp -a dotfiles/current/mac/. dist/mac-dotfiles
          echo "$VERSION" > dist/mac-dotfiles/.version
          cd dist
          zip -r mac-dotfiles-$VERSION.zip mac-dotfiles

      - name: Create release
        uses: ncipollo/release-action@95215a3cb6e6a1908b3c44e00b4fdb15548b1e09
        with:
          artifacts: |
            dist/ubuntu-dotfiles-${{ steps.version.outputs.value }}.zip,
            dist/mac-dotfiles-${{ steps.version.outputs.value }}.zip,
            bin/*
          commit: ${{ github.sha }}
          tag: "v${{ steps.version.outputs.value }}"
          name: "Version ${{ steps.version.outputs.value }}"
          token: ${{ secrets.GITHUB_TOKEN }}
